create table country
(
    id   integer generated by default as identity,
    name varchar(255),
    primary key (id)
);
create table trip
(
    id               integer generated by default as identity,
    destination_name varchar(255),
    finish_date      varchar(255),
    img_url          varchar(255),
    start_date       varchar(255),
    trip_notes       varchar(255),
    country_id       integer not null,
    primary key (id)
);
alter table trip
    add constraint FK77mvketix9pv0ibyxu0fiskl3 foreign key (country_id) references country;
